on:
  workflow_dispatch:
  push:
   branches: 
     - 'rb-**'
     
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch     
      - id: foo
        uses: taetaetae/helloWorld@v1.1
        with:
          base-branch: master
          compare-branch: ${{ steps.extract_branch.outputs.branch }}
          token: ??
      - run: echo ${{ steps.foo.outputs.diff-body }}
        shell: bash
