on:
  workflow_dispatch:
  
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: foo
        uses: taetaetae/helloWorld@v1.1
        with:
          base-branch: master
          compare-branch: rb
          token: ??
      - run: echo ${{ steps.foo.outputs.diff-body }}
        shell: bash
